INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (1,0,'Beret','head_1',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (2,0,'Beret','head_1',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (3,0,'Casque en fer','head_2',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (4,0,'Casque en fer','head_2',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (5,0,'Chapel de fer','head_3',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (6,0,'Chapel de fer','head_3',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (7,0,'Visière de fer','head_4',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (8,0,'Visière de fer','head_4',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (9,0,'Couvre chef en cuir','head_11',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (10,0,'Couvre chef en cuir','head_11',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (11,0,'Casque en cuir','head_12',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (12,0,'Casque en cuir','head_12',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (13,0,'Casque d''écuyer','head_13',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (14,0,'Casque d''écuyer','head_13',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (15,0,'Casque du gardien de la porte','head_14',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (16,0,'Casque du gardien de la porte','head_14',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (17,0,'Bandeau en corde','head_21',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (18,0,'Bandeau en corde','head_21',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (19,0,'Tête d''ours','head_22',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (20,0,'Tête d''ours','head_22',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (21,0,'Casque du Trax','head_23',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (22,0,'Casque du Trax','head_23',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (23,0,'Casque de l''Hoplomacus','head_24',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (24,0,'Casque de l''Hoplomacus','head_24',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (25,0,'Casque du Scissor','head_25',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (26,0,'Casque du Scissor','head_25',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (27,0,'Casque du Secutor','head_26',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (28,0,'Casque du Secutor','head_26',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (29,0,'Casque du Samnite','head_27',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (30,0,'Casque du Samnite','head_27',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (31,0,'Casque du Myrmidon','head_28',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (32,0,'Casque du Myrmidon','head_28',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (33,0,'Casque de l''hoplites','head_29',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (34,0,'Casque de l''hoplites','head_29',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (35,0,'Casque du centurion','head_30',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (36,0,'Casque du centurion','head_30',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (37,0,'Casque du Berzerker','head_33',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (38,0,'Casque du Berzerker','head_33',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (39,0,'Casque du Berzerker','head_33',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (40,0,'Heaume du Paladin','head_34',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (41,0,'Heaume du Paladin','head_34',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (42,0,'Heaume du Paladin','head_34',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (43,0,'Heaume du Purgateur','head_35',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (44,0,'Heaume du Purgateur','head_35',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (45,0,'Heaume du Purgateur','head_35',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (46,0,'Casque du Chevalier Blanc','head_36',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (47,0,'Casque du Chevalier Blanc','head_36',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (48,0,'Casque du Chevalier Blanc','head_36',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (49,0,'Bassinet des Executants','head_37',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (50,0,'Bassinet des Executants','head_37',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (51,0,'Bassinet des Executants','head_37',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (52,0,'Klappvisor de l''Expéditionnaire','head_38',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (53,0,'Klappvisor de l''Expéditionnaire','head_38',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (54,0,'Klappvisor de l''Expéditionnaire','head_38',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (55,0,'Heaume de la garde royale','head_5',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (56,0,'Heaume de la garde royale','head_5',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (57,0,'Heaume de la garde royale','head_5',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (58,0,'Casque du dernier Gaulois','head_15',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (59,0,'Casque du dernier Gaulois','head_15',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (60,0,'Casque du dernier Gaulois','head_15',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (61,0,'Visière du Guerriero','head_10',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (62,0,'Visière du Guerriero','head_10',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (63,0,'Visière du Guerriero','head_10',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (64,0,'Casque du Samourai','head_20',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (65,0,'Casque du Samourai','head_20',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (66,0,'Casque du Samourai','head_20',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (67,0,'Bi-cornes du roi Germanique','head_6',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (68,0,'Bi-cornes du roi Germanique','head_6',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (69,0,'Bi-cornes du roi Germanique','head_6',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (70,0,'Casque en Or de l''Empereur','head_7',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (71,0,'Casque en Or de l''Empereur','head_7',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (72,0,'Casque en Or de l''Empereur','head_7',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (73,0,'Heaume du Sans-âme','head_8',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (74,0,'Heaume du Sans-âme','head_8',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (75,0,'Heaume du Sans-âme','head_8',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (76,0,'Casque du Yersine','head_9',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (77,0,'Casque du Yersine','head_9',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (78,0,'Casque du Yersine','head_9',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (79,0,'Casque des gardiens du Sanctuaire','head_39',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (80,0,'Casque des gardiens du Sanctuaire','head_39',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (81,0,'Casque des gardiens du Sanctuaire','head_39',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (82,0,'Heaume du premier Templier','head_40',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (83,0,'Heaume du premier Templier','head_40',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (84,0,'Heaume du premier Templier','head_40',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (85,0,'Heaume des fils du Valhalla','head_16',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (86,0,'Heaume des fils du Valhalla','head_16',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (87,0,'Masque de Rhaal''Zath','head_17',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (88,0,'Masque de Rhaal''Zath','head_17',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (89,0,'Casque du Damné Boultag','head_18',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (90,0,'Casque du Damné Boultag','head_18',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (91,0,'Vision du Bushi Yamino','head_19',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (92,0,'Vision du Bushi Yamino','head_19',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (93,0,'Orchestrateur de l''Unique','head_31',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (94,0,'Visage du Serviteur du Mal','head_32',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (95,1,'Etoffe de cuir','body_1',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (96,1,'Etoffe de cuir','body_1',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (97,1,'Cage en fer','body_2',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (98,1,'Cage en fer','body_2',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (99,1,'Plastron de fer','body_3',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (100,1,'Plastron de fer','body_3',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (101,1,'Buste de fer','body_4',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (102,1,'Buste de fer','body_4',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (103,1,'Plastron en cuir','body_11',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (104,1,'Plastron en cuir','body_11',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (105,1,'Intégral en cuir','body_12',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (106,1,'Intagral en cuir','body_12',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (107,1,'Tunique d''écuyer','body_13',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (108,1,'Tunique d''écuyer','body_13',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (109,1,'Armure du gardien de la porte','body_14',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (110,1,'Armure du gardien de la porte','body_14',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (111,1,'Tunique rayée','body_21',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (112,1,'Tunique rayée','body_21',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (113,1,'Habit du forestier','body_22',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (114,1,'Habit du forestier','body_22',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (115,1,'Epaulière droite du Trax','body_23',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (116,1,'Epaulière droite du Trax','body_23',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (117,1,'Cotte de mailles de l''Hoplomacus','body_24',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (118,1,'Cotte de mailles de l''Hoplomacus','body_24',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (119,1,'Epaulière droite du Scissor','body_25',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (120,1,'Epaulière droite du Scissor','body_25',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (121,1,'Epaulière gauche du Secutor','body_26',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (122,1,'Epaulière gauche du Secutor','body_26',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (123,1,'Epaulière droite du Samnite','body_27',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (124,1,'Epaulière droite du Samnite','body_27',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (125,1,'Cotte de mailles du Myrmidon','body_28',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (126,1,'Cotte de mailles du Myrmidon','body_28',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (127,1,'Plastron échancré de l''hoplite','body_29',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (128,1,'Plastron échancré de l''hoplite','body_29',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (129,1,'Plastron du centurion','body_30',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (130,1,'Plastron du centurion','body_30',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (131,1,'Epaulière du Berzerker','body_33',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (132,1,'Epaulière du Berzerker','body_33',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (133,1,'Epaulière du Berzerker','body_33',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (134,1,'Armure du Paladin','body_34',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (135,1,'Armure du Paladin','body_34',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (136,1,'Armure du Paladin','body_34',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (137,1,'Haut du Purgateur','body_35',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (138,1,'Haut du Purgateur','body_35',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (139,1,'Haut du Purgateur','body_35',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (140,1,'Armure du Chevalier Blanc','body_36',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (141,1,'Armure du Chevalier Blanc','body_36',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (142,1,'Armure du Chevalier Blanc','body_36',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (143,1,'Cuirasse des Executants','body_37',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (144,1,'Cuirasse des Executants','body_37',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (145,1,'Cuirasse des Executants','body_37',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (146,1,'Armure lourde de l''Expéditionnaire','body_38',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (147,1,'Armure lourde de l''Expéditionnaire','body_38',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (148,1,'Armure lourde de l''Expéditionnaire','body_38',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (149,1,'Armure à noyau de la garde royale','body_5',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (150,1,'Armure à noyau de la garde royale','body_5',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (151,1,'Armure à noyau de la garde royale','body_5',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (152,1,'Brigandine du dernier Gaulois','body_15',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (153,1,'Brigandine du dernier Gaulois','body_15',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (154,1,'Brigandine du dernier Gaulois','body_15',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (155,1,'Armatura du Guerriero','body_10',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (156,1,'Armatura du Guerriero','body_10',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (157,1,'Armatura du Guerriero','body_10',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (158,1,'Armure du Samourai','body_20',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (159,1,'Armure du Samourai','body_20',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (160,1,'Armure du Samourai','body_20',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (161,1,'Torse du roi Germanique','body_6',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (162,1,'Torse du roi Germanique','body_6',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (163,1,'Torse du roi Germanique','body_6',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (164,1,'Armure en Or de l''Empereur','body_7',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (165,1,'Armure en Or de l''Empereur','body_7',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (166,1,'Armure en Or de l''Empereur','body_7',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (167,1,'Corps du Sans-âme','body_8',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (168,1,'Corps du Sans-âme','body_8',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (169,1,'Corps du Sans-âme','body_8',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (170,1,'Robe du Yersine','body_9',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (171,1,'Robe du Yersine','body_9',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (172,1,'Robe du Yersine','body_9',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (173,1,'Plastron des gardiens du Sanctuaire','body_39',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (174,1,'Plastron des gardiens du Sanctuaire','body_39',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (175,1,'Plastron des gardiens du Sanctuaire','body_39',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (176,1,'Armure lourde du premier Templier','body_40',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (177,1,'Armure lourde du premier Templier','body_40',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (178,1,'Armure lourde du premier Templier','body_40',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (179,1,'Haubert des fils du Valhalla','body_16',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (180,1,'Haubert des fils du Valhalla','body_16',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (181,1,'Buste de Rhaal''Zath','body_17',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (182,1,'Buste de Rhaal''Zath','body_17',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (183,1,'Protection du Damné Boultag','body_18',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (184,1,'Protection du Damné Boultag','body_18',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (185,1,'Cotte à épines du Bushi Yamino','body_19',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (186,1,'Cotte à épines du Bushi Yamino','body_19',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (187,1,'Invincible de l''Unique','body_31',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (188,1,'Immunité du Serviteur du Mal','body_32',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (189,2,'Moufle de cuir gauche','hand_left_1',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (190,2,'Moufle de cuir gauche','hand_left_1',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (191,2,'Poignée gauche en fer','hand_left_2',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (192,2,'Poignée gauche en fer','hand_left_2',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (193,2,'Gant gauche de fer','hand_left_3',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (194,2,'Gant gauche de fer','hand_left_3',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (195,2,'Gantelet gauche de fer','hand_left_4',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (196,2,'Gantelet gauche de fer','hand_left_4',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (197,2,'Mitaine gauche de l''archet','hand_left_11',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (198,2,'Mitaine gauche de l''archet','hand_left_11',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (199,2,'Gant court gauche en cuir','hand_left_12',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (200,2,'Gant court gauche en cuir','hand_left_12',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (201,2,'Gantelet gauche d''écuyer','hand_left_13',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (202,2,'Gantelet gauche d''écuyer','hand_left_13',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (203,2,'Gantelet gauche du gardien de la porte','hand_left_14',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (204,2,'Gantelet gauche du gardien de la porte','hand_left_14',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (205,2,'Avant-bras gauche en corde','hand_left_21',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (206,2,'Avant-bras gauche en corde','hand_left_21',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (207,2,'Avant-bras gauche du forestier','hand_left_22',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (208,2,'Avant-bras gauche du forestier','hand_left_22',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (209,2,'Avant-bras gauche du Trax','hand_left_23',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (210,2,'Avant-bras gauche du Trax','hand_left_23',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (211,2,'Avant-bras gauche de l''Hoplomacus','hand_left_24',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (212,2,'Avant-bras gauche de l''Hoplomacus','hand_left_24',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (213,2,'Gantelet gauche du Scissor','hand_left_25',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (214,2,'Gantelet gauche du Scissor','hand_left_25',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (215,2,'Moufle gauche de combat du Secutor','hand_left_26',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (216,2,'Moufle gauche de combat du Secutor','hand_left_26',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (217,2,'Gantelet gauche en fer du Samnite','hand_left_27',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (218,2,'Gantelet gauche en fer du Samnite','hand_left_27',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (219,2,'Main gauche du Myrmidon','hand_left_28',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (220,2,'Main gauche du Myrmidon','hand_left_28',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (221,2,'Avant-bras gauche de l''hoplite','hand_left_29',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (222,2,'Avant-bras gauche de l''hoplite','hand_left_29',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (223,2,'Gantelet gauche du centurion','hand_left_30',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (224,2,'Gantelet gauche du centurion','hand_left_30',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (225,2,'Doigts de sang gauches du Berzerker','hand_left_33',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (226,2,'Doigts de sang gauches du Berzerker','hand_left_33',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (227,2,'Doigts de sang gauches du Berzerker','hand_left_33',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (228,2,'Gantelet à lamelles gauche du Paladin','hand_left_34',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (229,2,'Gantelet à lamelles gauche du Paladin','hand_left_34',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (230,2,'Gantelet à lamelles gauche du Paladin','hand_left_34',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (231,2,'Paume gauche inversée du Purgateur','hand_left_35',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (232,2,'Paume gauche inversée du Purgateur','hand_left_35',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (233,2,'Paume gauche inversée du Purgateur','hand_left_35',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (234,2,'Poing gauche du Chevalier Blanc','hand_left_36',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (235,2,'Poing gauche du Chevalier Blanc','hand_left_36',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (236,2,'Poing gauche du Chevalier Blanc','hand_left_36',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (237,2,'Rond-doigts gauche des Executants','hand_left_37',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (238,2,'Rond-doigts gauche des Executants','hand_left_37',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (239,2,'Rond-doigts gauche des Executants','hand_left_37',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (240,2,'Hexagone gauche de l''Expéditionnaire','hand_left_38',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (241,2,'Hexagone gauche de l''Expéditionnaire','hand_left_38',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (242,2,'Hexagone gauche de l''Expéditionnaire','hand_left_38',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (243,2,'Main gauche de la garde royale','hand_left_5',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (244,2,'Main gauche de la garde royale','hand_left_5',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (245,2,'Main gauche de la garde royale','hand_left_5',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (246,2,'Baffe gauche du dernier Gaulois','hand_left_15',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (247,2,'Baffe gauche du dernier Gaulois','hand_left_15',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (248,2,'Baffe gauche du dernier Gaulois','hand_left_15',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (249,2,'Avant-bras gauche creux du Guerriero','hand_left_10',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (250,2,'Avant-bras gauche creux du Guerriero','hand_left_10',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (251,2,'Avant-bras gauche creux du Guerriero','hand_left_10',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (252,2,'Gantelet gauche du Samourai','hand_left_20',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (253,2,'Gantelet gauche du Samourai','hand_left_20',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (254,2,'Gantelet gauche du Samourai','hand_left_20',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (255,2,'Poignée gauche du roi Germanique','hand_left_6',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (256,2,'Poignée gauche du roi Germanique','hand_left_6',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (257,2,'Poignée gauche du roi Germanique','hand_left_6',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (258,2,'Gantelet gauche serti de l''Empereur','hand_left_7',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (259,2,'Gantelet gauche serti de l''Empereur','hand_left_7',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (260,2,'Gantelet gauche serti de l''Empereur','hand_left_7',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (261,2,'Revers gauche du Sans-âme','hand_left_8',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (262,2,'Revers gauche du Sans-âme','hand_left_8',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (263,2,'Revers gauche du Sans-âme','hand_left_8',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (264,2,'Griffes gauches du Yersine','hand_left_9',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (265,2,'Griffes gauches du Yersine','hand_left_9',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (266,2,'Griffes gauches du Yersine','hand_left_9',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (267,2,'Joyau gauche des gardiens du Sanctuaire','hand_left_39',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (268,2,'Joyau gauche des gardiens du Sanctuaire','hand_left_39',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (269,2,'Joyau gauche des gardiens du Sanctuaire','hand_left_39',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (270,2,'Promesse Ouest du premier Templier','hand_left_40',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (271,2,'Promesse Ouest du premier Templier','hand_left_40',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (272,2,'Promesse Ouest du premier Templier','hand_left_40',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (273,2,'Levée gauche des fils du Valhalla','hand_left_16',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (274,2,'Levée gauche des fils du Valhalla','hand_left_16',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (275,2,'Liane gauche de Rhaal''Zath','hand_left_17',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (276,2,'Liane gauche de Rhaal''Zath','hand_left_17',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (277,2,'Saisie gauche du Damné Boultag','hand_left_18',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (278,2,'Saisie gauche du Damné Boultag','hand_left_18',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (279,2,'Trahison gauche du Bushi Yamino','hand_left_19',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (280,2,'Trahison gauche du Bushi Yamino','hand_left_19',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (281,2,'Alpha de l''Unique','hand_left_31',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (282,2,'Chaos du Serviteur du Mal','hand_left_32',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (283,3,'Moufle de cuir droite','hand_right_1',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (284,3,'Moufle de cuir droite','hand_right_1',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (285,3,'Poignée droite en fer','hand_right_2',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (286,3,'Poignée droite en fer','hand_right_2',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (287,3,'Gant droit de fer','hand_right_3',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (288,3,'Gant droit de fer','hand_right_3',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (289,3,'Gantelet droit de fer','hand_right_4',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (290,3,'Gantelet droit de fer','hand_right_4',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (291,3,'Mitaine droite de l''archet','hand_right_11',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (292,3,'Mitaine droite de l''archet','hand_right_11',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (293,3,'Gant court droit en cuir','hand_right_12',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (294,3,'Gant court droit en cuir','hand_right_12',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (295,3,'Gantelet droit d''écuyer','hand_right_13',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (296,3,'Gantelet droit d''écuyer','hand_right_13',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (297,3,'Gantelet droit du gardien de la porte','hand_right_14',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (298,3,'Gantelet droit du gardien de la porte','hand_right_14',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (299,3,'Avant-bras droit en corde','hand_right_21',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (300,3,'Avant-bras droit en corde','hand_right_21',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (301,3,'Avant-bras droit du forestier','hand_right_22',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (302,3,'Avant-bras droit du forestier','hand_right_22',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (303,3,'Avant-bras droit du Trax','hand_right_23',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (304,3,'Avant-bras droit du Trax','hand_right_23',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (305,3,'Avant-bras droit de l''Hoplomacus','hand_right_24',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (306,3,'Avant-bras droit de l''Hoplomacus','hand_right_24',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (307,3,'Gantelet droit du Scissor','hand_right_25',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (308,3,'Gantelet droit du Scissor','hand_right_25',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (309,3,'Moufle droite de combat du Secutor','hand_right_26',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (310,3,'Moufle droite de combat du Secutor','hand_right_26',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (311,3,'Gantelet droit en fer du Samnite','hand_right_27',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (312,3,'Gantelet droit en fer du Samnite','hand_right_27',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (313,3,'Main droite du Myrmidon','hand_right_28',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (314,3,'Main droite du Myrmidon','hand_right_28',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (315,3,'Avant-bras droit de l''hoplite','hand_right_29',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (316,3,'Avant-bras droit de l''hoplite','hand_right_29',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (317,3,'Gantelet droit du centurion','hand_right_30',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (318,3,'Gantelet droit du centurion','hand_right_30',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (319,3,'Doigts de sang droit du Berzerker','hand_right_33',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (320,3,'Doigts de sang droit du Berzerker','hand_right_33',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (321,3,'Doigts de sang droit du Berzerker','hand_right_33',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (322,3,'Gantelet à lamelles droit du Paladin','hand_right_34',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (323,3,'Gantelet à lamelles droit du Paladin','hand_right_34',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (324,3,'Gantelet à lamelles droit du Paladin','hand_right_34',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (325,3,'Paume droite inversée du Purgateur','hand_right_35',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (326,3,'Paume droite inversée du Purgateur','hand_right_35',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (327,3,'Paume droite inversée du Purgateur','hand_right_35',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (328,3,'Poing droit du Chevalier Blanc','hand_right_36',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (329,3,'Poing droit du Chevalier Blanc','hand_right_36',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (330,3,'Poing droit du Chevalier Blanc','hand_right_36',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (331,3,'Rond-doigts droit des Executants','hand_right_37',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (332,3,'Rond-doigts droit des Executants','hand_right_37',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (333,3,'Rond-doigts droit des Executants','hand_right_37',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (334,3,'Hexagone droit de l''Expéditionnaire','hand_right_38',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (335,3,'Hexagone droit de l''Expéditionnaire','hand_right_38',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (336,3,'Hexagone droit de l''Expéditionnaire','hand_right_38',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (337,3,'Main droite de la garde royale','hand_right_5',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (338,3,'Main droite de la garde royale','hand_right_5',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (339,3,'Main droite de la garde royale','hand_right_5',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (340,3,'Baffe droite du dernier Gaulois','hand_right_15',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (341,3,'Baffe droite du dernier Gaulois','hand_right_15',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (342,3,'Baffe droite du dernier Gaulois','hand_right_15',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (343,3,'Avant-bras droit creux du Guerriero','hand_right_10',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (344,3,'Avant-bras droit creux du Guerriero','hand_right_10',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (345,3,'Avant-bras droit creux du Guerriero','hand_right_10',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (346,3,'Gantelet droit du Samourai','hand_right_20',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (347,3,'Gantelet droit du Samourai','hand_right_20',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (348,3,'Gantelet droit du Samourai','hand_right_20',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (349,3,'Poignée droite du roi Germanique','hand_right_6',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (350,3,'Poignée droite du roi Germanique','hand_right_6',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (351,3,'Poignée droite du roi Germanique','hand_right_6',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (352,3,'Gantelet droit serti de l''Empereur','hand_right_7',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (353,3,'Gantelet droit serti de l''Empereur','hand_right_7',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (354,3,'Gantelet droit serti de l''Empereur','hand_right_7',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (355,3,'Revers droit du Sans-âme','hand_right_8',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (356,3,'Revers droit du Sans-âme','hand_right_8',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (357,3,'Revers droit du Sans-âme','hand_right_8',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (358,3,'Griffes droites du Yersine','hand_right_9',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (359,3,'Griffes droites du Yersine','hand_right_9',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (360,3,'Griffes droites du Yersine','hand_right_9',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (361,3,'Joyau droit des gardiens du Sanctuaire','hand_right_39',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (362,3,'Joyau droit des gardiens du Sanctuaire','hand_right_39',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (363,3,'Joyau droit des gardiens du Sanctuaire','hand_right_39',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (364,3,'Promesse Est du premier Templier','hand_right_40',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (365,3,'Promesse Est du premier Templier','hand_right_40',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (366,3,'Promesse Est du premier Templier','hand_right_40',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (367,3,'Levée droite des fils du Valhalla','hand_right_16',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (368,3,'Levée droite des fils du Valhalla','hand_right_16',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (369,3,'Liane droite de Rhaal''Zath','hand_right_17',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (370,3,'Liane droite de Rhaal''Zath','hand_right_17',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (371,3,'Saisie droite du Damné Boultag','hand_right_18',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (372,3,'Saisie droite du Damné Boultag','hand_right_18',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (373,3,'Trahison droite du Bushi Yamino','hand_right_19',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (374,3,'Trahison droite du Bushi Yamino','hand_right_19',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (375,3,'Omega de l''Unique','hand_right_31',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (376,3,'Anihilation du Serviteur du Mal','hand_right_32',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (377,4,'Protège tibias gauche de cuir','feet_left_1',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (378,4,'Protège tibias gauche de cuir','feet_left_1',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (379,4,'Protège tibias gauche en fer','feet_left_2',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (380,4,'Protège tibias gauche en fer','feet_left_2',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (381,4,'Jambière gauche de fer','feet_left_3',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (382,4,'Jambière gauche de fer','feet_left_3',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (383,4,'Jambière pointue gauche de fer','feet_left_4',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (384,4,'Jambière pointue gauche de fer','feet_left_4',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (385,4,'Soulier gauche de l''archet','feet_left_11',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (386,4,'Soulier gauche de l''archet','feet_left_11',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (387,4,'Botte gauche en cuir','feet_left_12',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (388,4,'Botte gauche en cuir','feet_left_12',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (389,4,'Botte gauche rembourrée d''écuyer','feet_left_13',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (390,4,'Botte gauche rembourrée d''écuyer','feet_left_13',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (391,4,'Chausse à lacet gauche du gardien de la porte','feet_left_14',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (392,4,'Chausse à lacet gauche du gardien de la porte','feet_left_14',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (393,4,'Tabis gauche en corde','feet_left_21',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (394,4,'Tabis gauche en corde','feet_left_21',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (395,4,'Bottine gauche du forestier','feet_left_22',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (396,4,'Bottine gauche du forestier','feet_left_22',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (397,4,'Chaussure gauche du Trax','feet_left_23',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (398,4,'Chaussure gauche du Trax','feet_left_23',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (399,4,'Chevillère gauche de l''Hoplomacus','feet_left_24',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (400,4,'Chevillère gauche de l''Hoplomacus','feet_left_24',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (401,4,'Spartiate gauche du Scissor','feet_left_25',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (402,4,'Spartiate gauche du Scissor','feet_left_25',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (403,4,'Botte renforcée gauche de combat du Secutor','feet_left_26',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (404,4,'Botte renforcée gauche de combat du Secutor','feet_left_26',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (405,4,'Calceus gauche du Samnite','feet_left_27',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (406,4,'Calceus gauche du Samnite','feet_left_27',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (407,4,'Socci gauche du Myrmidon','feet_left_28',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (408,4,'Socci gauche du Myrmidon','feet_left_28',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (409,4,'Spartiate montante gauche de l''hoplite','feet_left_29',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (410,4,'Spartiate montante gauche de l''hoplite','feet_left_29',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (411,4,'Sandale montante gauche du centurion','feet_left_30',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (412,4,'Sandale montante gauche du centurion','feet_left_30',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (413,4,'Socci rougeoyant gauche du Berzerker','feet_left_33',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (414,4,'Socci rougeoyant gauche du Berzerker','feet_left_33',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (415,4,'Socci rougeoyant gauche du Berzerker','feet_left_33',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (416,4,'Semelle-souche gauche du Paladin','feet_left_34',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (417,4,'Semelle-souche gauche du Paladin','feet_left_34',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (418,4,'Semelle-souche gauche du Paladin','feet_left_34',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (419,4,'Coque gauche du Purgateur','feet_left_35',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (420,4,'Coque gauche du Purgateur','feet_left_35',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (421,4,'Coque gauche du Purgateur','feet_left_35',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (422,4,'Soleret gauche du Chevalier Blanc','feet_left_36',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (423,4,'Soleret gauche du Chevalier Blanc','feet_left_36',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (424,4,'Soleret gauche du Chevalier Blanc','feet_left_36',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (425,4,'Pointe gauche des Executants','feet_left_37',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (426,4,'Pointe gauche des Executants','feet_left_37',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (427,4,'Pointe gauche des Executants','feet_left_37',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (428,4,'Chausse moutante gauche de l''Expéditionnaire','feet_left_38',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (429,4,'Chausse moutante gauche de l''Expéditionnaire','feet_left_38',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (430,4,'Chausse moutante gauche de l''Expéditionnaire','feet_left_38',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (431,4,'Sabaton gauche de la garde royale','feet_left_5',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (432,4,'Sabaton gauche de la garde royale','feet_left_5',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (433,4,'Sabaton gauche de la garde royale','feet_left_5',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (434,4,'Haute-brogue gauche du dernier Gaulois','feet_left_15',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (435,4,'Haute-brogue gauche du dernier Gaulois','feet_left_15',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (436,4,'Haute-brogue gauche du dernier Gaulois','feet_left_15',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (437,4,'Scarpa gauche creux du Guerriero','feet_left_10',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (438,4,'Scarpa gauche creux du Guerriero','feet_left_10',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (439,4,'Scarpa gauche creux du Guerriero','feet_left_10',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (440,4,'Waraji gauche de combat','feet_left_20',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (441,4,'Waraji gauche de combat','feet_left_20',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (442,4,'Waraji gauche de combat','feet_left_20',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (443,4,'Pointe gauche du roi Germanique','feet_left_6',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (444,4,'Pointe gauche du roi Germanique','feet_left_6',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (445,4,'Pointe gauche du roi Germanique','feet_left_6',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (446,4,'Chausse d''Or gauche de l''Empereur','feet_left_7',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (447,4,'Chausse d''Or gauche de l''Empereur','feet_left_7',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (448,4,'Chausse d''Or gauche de l''Empereur','feet_left_7',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (449,4,'Ronde-botte gauche du Sans-âme','feet_left_8',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (450,4,'Ronde-botte gauche du Sans-âme','feet_left_8',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (451,4,'Ronde-botte gauche du Sans-âme','feet_left_8',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (452,4,'Epine-vrille gauche du Yersine','feet_left_9',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (453,4,'Epine-vrille gauche du Yersine','feet_left_9',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (454,4,'Epine-vrille gauche du Yersine','feet_left_9',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (455,4,'Soleret gauche des gardiens du Sanctuaire','feet_left_39',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (456,4,'Soleret gauche des gardiens du Sanctuaire','feet_left_39',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (457,4,'Soleret gauche des gardiens du Sanctuaire','feet_left_39',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (458,4,'Humble chausse Ouest du premier Templier','feet_left_40',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (459,4,'Humble chausse Ouest du premier Templier','feet_left_40',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (460,4,'Humble chausse Ouest du premier Templier','feet_left_40',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (461,4,'Bottine gauche des fils du Valhalla','feet_left_16',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (462,4,'Bottine gauche des fils du Valhalla','feet_left_16',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (463,4,'Scubotte gauche de Rhaal''Zath','feet_left_17',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (464,4,'Scubotte gauche de Rhaal''Zath','feet_left_17',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (465,4,'Protège jambe gauche du Damné Boultag','feet_left_18',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (466,4,'Protège jambe gauche du Damné Boultag','feet_left_18',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (467,4,'Foule-terre gauche du Bushi Yamino','feet_left_19',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (468,4,'Foule-terre gauche du Bushi Yamino','feet_left_19',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (469,4,'Appuie de l''Unique','feet_left_31',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (470,4,'Désolation du Serviteur du Mal','feet_left_32',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (471,5,'Protège tibias droit de cuir','feet_right_1',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (472,5,'Protège tibias droit de cuir','feet_right_1',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (473,5,'Protège tibias droit en fer','feet_right_2',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (474,5,'Protège tibias droit en fer','feet_right_2',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (475,5,'Jambière droite de fer','feet_right_3',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (476,5,'Jambière droite de fer','feet_right_3',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (477,5,'Jambière pointue droite de fer','feet_right_4',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (478,5,'Jambière pointue droite de fer','feet_right_4',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (479,5,'Soulier droit de l''archet','feet_right_11',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (480,5,'Soulier droit de l''archet','feet_right_11',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (481,5,'Botte droite en cuir','feet_right_12',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (482,5,'Botte droite en cuir','feet_right_12',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (483,5,'Botte droite rembourrée d''écuyer','feet_right_13',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (484,5,'Botte droite rembourrée d''écuyer','feet_right_13',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (485,5,'Chausse à lacet droite du gardien de la porte','feet_right_14',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (486,5,'Chausse à lacet droite du gardien de la porte','feet_right_14',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (487,5,'Tabis droit en corde','feet_right_21',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (488,5,'Tabis droit en corde','feet_right_21',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (489,5,'Bottine droite du forestier','feet_right_22',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (490,5,'Bottine droite du forestier','feet_right_22',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (491,5,'Chaussure droite du Trax','feet_right_23',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (492,5,'Chaussure droite du Trax','feet_right_23',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (493,5,'Chevillère droite de l''Hoplomacus','feet_right_24',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (494,5,'Chevillère droite de l''Hoplomacus','feet_right_24',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (495,5,'Spartiate droite du Scissor','feet_right_25',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (496,5,'Spartiate droite du Scissor','feet_right_25',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (497,5,'Botte renforcée droite de combat du Secutor','feet_right_26',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (498,5,'Botte renforcée droite de combat du Secutor','feet_right_26',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (499,5,'Calceus droit du Samnite','feet_right_27',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (500,5,'Calceus droit du Samnite','feet_right_27',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (501,5,'Socci droit du Myrmidon','feet_right_28',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (502,5,'Socci droit du Myrmidon','feet_right_28',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (503,5,'Spartiate montante droite de l''hoplite','feet_right_29',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (504,5,'Spartiate montante droite de l''hoplite','feet_right_29',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (505,5,'Sandale montante droite du centurion','feet_right_30',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (506,5,'Sandale montante droite du centurion','feet_right_30',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (507,5,'Socci rougeoyant droit du Berzerker','feet_right_33',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (508,5,'Socci rougeoyant droit du Berzerker','feet_right_33',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (509,5,'Socci rougeoyant droit du Berzerker','feet_right_33',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (510,5,'Semelle-souche droite du Paladin','feet_right_34',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (511,5,'Semelle-souche droite du Paladin','feet_right_34',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (512,5,'Semelle-souche droite du Paladin','feet_right_34',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (513,5,'Coque droite du Purgateur','feet_right_35',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (514,5,'Coque droite du Purgateur','feet_right_35',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (515,5,'Coque droite du Purgateur','feet_right_35',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (516,5,'Soleret droit du Chevalier Blanc','feet_right_36',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (517,5,'Soleret droit du Chevalier Blanc','feet_right_36',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (518,5,'Soleret droit du Chevalier Blanc','feet_right_36',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (519,5,'Pointe droite des Executants','feet_right_37',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (520,5,'Pointe droite des Executants','feet_right_37',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (521,5,'Pointe droite des Executants','feet_right_37',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (522,5,'Chausse moutante droite de l''Expéditionnaire','feet_right_38',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (523,5,'Chausse moutante droite de l''Expéditionnaire','feet_right_38',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (524,5,'Chausse moutante droite de l''Expéditionnaire','feet_right_38',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (525,5,'Sabaton droit de la garde royale','feet_right_5',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (526,5,'Sabaton droit de la garde royale','feet_right_5',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (527,5,'Sabaton droit de la garde royale','feet_right_5',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (528,5,'Haute-brogue droite du dernier Gaulois','feet_right_15',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (529,5,'Haute-brogue droite du dernier Gaulois','feet_right_15',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (530,5,'Haute-brogue droite du dernier Gaulois','feet_right_15',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (531,5,'Scarpa droit creux du Guerriero','feet_right_10',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (532,5,'Scarpa droit creux du Guerriero','feet_right_10',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (533,5,'Scarpa droit creux du Guerriero','feet_right_10',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (534,5,'Waraji droit de combat','feet_right_20',72);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (535,5,'Waraji droit de combat','feet_right_20',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (536,5,'Waraji droit de combat','feet_right_20',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (537,5,'Pointe droite du roi Germanique','feet_right_6',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (538,5,'Pointe droite du roi Germanique','feet_right_6',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (539,5,'Pointe droite du roi Germanique','feet_right_6',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (540,5,'Chausse d''Or droite de l''Empereur','feet_right_7',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (541,5,'Chausse d''Or droite de l''Empereur','feet_right_7',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (542,5,'Chausse d''Or droite de l''Empereur','feet_right_7',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (543,5,'Ronde-botte droite du Sans-âme','feet_right_8',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (544,5,'Ronde-botte droite du Sans-âme','feet_right_8',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (545,5,'Ronde-botte droite du Sans-âme','feet_right_8',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (546,5,'Epine-vrille droite du Yersine','feet_right_9',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (547,5,'Epine-vrille droite du Yersine','feet_right_9',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (548,5,'Epine-vrille droite du Yersine','feet_right_9',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (549,5,'Soleret droit des gardiens du Sanctuaire','feet_right_39',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (550,5,'Soleret droit des gardiens du Sanctuaire','feet_right_39',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (551,5,'Soleret droit des gardiens du Sanctuaire','feet_right_39',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (552,5,'Humble chausse Ouest du premier Templier','feet_right_40',22);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (553,5,'Humble chausse Ouest du premier Templier','feet_right_40',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (554,5,'Humble chausse Ouest du premier Templier','feet_right_40',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (555,5,'Bottine droite des fils du Valhalla','feet_right_16',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (556,5,'Bottine droite des fils du Valhalla','feet_right_16',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (557,5,'Scubotte droite de Rhaal''Zath','feet_right_17',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (558,5,'Scubotte droite de Rhaal''Zath','feet_right_17',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (559,5,'Protège jambe droit du Damné Boultag','feet_right_18',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (560,5,'Protège jambe droit du Damné Boultag','feet_right_18',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (561,5,'Foule-terre droite du Bushi Yamino','feet_right_19',5);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (562,5,'Foule-terre droite du Bushi Yamino','feet_right_19',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (563,5,'Appel de l''Unique','feet_right_31',1);
INSERT INTO bank_item(bank_item_id,bank_item_membre,bank_item_name,bank_item_picture,bank_item_rarity) VALUES (564,5,'Calamité du Serviteur du Mal','feet_right_32',1);
